application controller findall test 추가
themoment-team/hellogsm-server pull request #114
Opened 2023-07-04 11:12 UTC by chanwoo00106

## 개요

findAll 기능 테스트 추가

## 본문

ApplicationController findall test를 추가합니다

### 변경

이전 코드에 type을 적지 않아서 추가를 했습니다

2023-07-04 12:17 UTC, YangSiJun528 requested changes

2023-07-04 12:17 UTC, YangSiJun528 commented on hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
> +        this.mockMvc.perform(get("/application/v1/application/all?page=0&size=1")
query param 문자열 안에 포함하지 말고 따로 정의해주세요.

[Request Parameters](https://docs.spring.io/spring-restdocs/docs/2.0.5.RELEASE/reference/html5/#documenting-your-api-request-parameters)
여기서 나오는 `.prarm()` 메서드 참고해서 수정해주세요.

다른 부분도 있을지 모르겠는데, 있으면 같이 수정해주세요.

2023-07-04 14:56 UTC, chanwoo00106 commented
아니 왜 close를 때려 ㅋㅋㅋㅋ
내 코드 찾고 있었잖아

2023-07-04 14:58 UTC, YangSiJun528 commented
> 아니 왜 close를 때려 ㅋㅋㅋㅋ 내 코드 찾고 있었잖아

???
아 로컬 브랜치 너무 많이 생겨서 정리했는데, 그때 브랜치 지워서 알아서 닫힌거 같음..
미안;;

2023-07-04 15:03 UTC, chanwoo00106 commented on hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
> +        this.mockMvc.perform(get("/application/v1/application/all?page=0&size=1")
나도 전에 해봤는데 이게 import가 안되더라

<img width="1090" alt="image" src="https://github.com/themoment-team/hello-gsm-back-v2/assets/57276315/b62f5328-3622-4797-8189-ec904b89307f">

2023-07-04 23:29 UTC, YangSiJun528 approved these changes

2023-07-05 00:06 UTC, chanwoo00106 commented on hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
> +        this.mockMvc.perform(get("/application/v1/application/all?page=0&size=1")
queryParameters 로 해결~

2023-07-05 00:06 UTC, merged