[#129] security config 설정 수정
themoment-team/hellogsm-server pull request #130
Opened 2023-07-05 15:12 UTC by chanwoo00106

## 개요

security config 설정을 수정했습니다

## 본문

- 403 response message를 수정했습니다
- 페이지별 권한 설정을 수정했습니다

### 변경

필요 없을  것 같은 회원 정보 수정 controller는 주석 처리만 하고 남겨두었습니다.

2023-07-05 15:19 UTC, YangSiJun528 requested changes

2023-07-05 15:19 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
> +                        Role.ROLE_USER.getRole()
user 도메인은 `ROLE_UNAUTHENTICATED`도 포함해줘야 해

2023-07-05 15:20 UTC, YangSiJun528 commented
그리고 최종제출 설정하는 url도 안보이는데, 빼먹은거 같음

2023-07-06 00:13 UTC, chanwoo00106 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
> +                        Role.ROLE_USER.getRole()
수정했어~

2023-07-06 00:38 UTC, YangSiJun528 approved these changes

2023-07-06 00:41 UTC, merged