원서 관련 서비스 javadoc 작성
themoment-team/hellogsm-server pull request #219
Opened 2023-09-16 10:30 UTC by jangwooooo

## 개요

`web/domain/application/service`경로에 존재하는 원서관련 서비스의 클래스, 메서드에 대하여 javadoc을 작성하였습니다.

### 피드백

javadoc작성이 처음이라서 보완할 부분이나 잘못한 부분 피드백 주시면 감사하겠습니다.

2023-09-16 11:41 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationForConsistencyImpl.java
> + * Identity 수정 시 원서를 수정하는 service implementation 입니다.
나머지 엔티티 이름은 한글로 작성했는데 `Identity` 만 영어로 작성했네요.
일관성 있게 `Identity`도 '본인인증 정보'로 변경하는게 좋겠습니다.

2023-09-16 12:04 UTC, YangSiJun528 requested changes
설명 자체는 좋다고 생각하는데, 너무 자세하게 설명해서 관리하기 까다로워 보입니다.

2023-09-16 12:04 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CascadeDeleteApplicationServiceImpl.java
> +     * 매개변수로 userId를 받아 해당 userId가 작성한 원서를 찾습니다. <br>
여기뿐만 아니라 메서드에 작성한 JavaDoc 전부 해당되는 내용입니다.
다른 부분도 일부 피드백하긴 하겠지만 제가 직접 피드백하지 않은 부분도 수정 부탁드려요.

### JavaDoc 피드백

메서드가 수행하는 역할을 설명하고, 내부 구현에 관해선 설명하지 않는게 좋아요.
JavaDoc에 작성된 정보는 외부에서 코드를 확인하지 않고 사용할 수 있는 정도면 충분합니다.
오히려 자세한 설명은 코드와 JavaDoc 내용을 일관성있게 지속적으로 관리해야 해서 효율이 떨어집니다.

문장 단위로 나눠서 설명드리겠습니다.

> 매개변수로 userId를 받아 해당 userId가 작성한 원서를 찾습니다.

원서를 찾는다는 부분만 있어도 충분합니다.
매개변수에 대한 설명은 `@param`을 통해 설명했으니 생략 가능합니다.

> 최종제출된 혹은 존재하지 않는 원서에 대한 삭제 요청이 발생할시 warn수준의 log를 찍습니다.

최종제출된 혹은 존재하지 않는 원서에 대한 삭제 요청은 무시된다고만 설명하는게 좋겠습니다.

내부 구현을 설명하지 않는 예시를 작성해보자면 아래처럼 되겠습니다.
그냥 예시니까 참고만 해주세요.

```
유저의 원서를 삭제합니다.
단, 최종제출된 혹은 존재하지 않는 원서에 대한 요청은 무시됩니다.

@param userId user의 pk값
```
### 참고

JavaDoc 작성에 관해서 잘 설명해주는 글 링크 남기겠습니다. 
https://johngrib.github.io/wiki/java/javadoc/

2023-09-16 12:04 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CreateApplicationServiceImpl.java
> +     * 찾은 본인인증 정보와 원서에 작성할 정보를 바탕으로 원서를 생성하고 DB에 저장합니다.
> 찾은 본인인증 정보와 원서에 작성할 정보를 바탕으로 원서를 생성하고 DB에 저장합니다.

앞서 말했듯, "DB에 저장합니다." 처럼 내부 구현이 드러나는 것보단 그냥 저장한다는 말이 더 좋아요.

2023-09-16 12:04 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationForConsistencyImpl.java
> +     * 원서를 찾았다면 기존 원서와 수정된 본인인증 정보를 바탕으로 새로운 원서 객체를 하고 저장합니다. <br>
> 원서를 찾았다면 기존 원서와 수정된 본인인증 정보를 바탕으로 새로운 원서 객체를 하고 저장합니다.

"원서 객체를 하고 저장합니다."

"수정하고 저장합니다." 인데 오타나신건가요?

2023-09-16 12:04 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationStatusServiceImpl.java
> +     * 매개변수로 변경될 유저의 pk값과 변경할 원서상태 정보를 받아 userId로 원서를 찾습니다. <br>
> 매개변수로 변경될 유저의 pk값과 변경할 원서상태 정보를 받아 ...

`@param`에서 설명하니까 매개변수 설명하지 않아도 되고,

> ... userId로 원서를 찾습니다.

내부 구현은 드러나지 않는게 좋습니다.

2023-09-17 06:44 UTC, jangwooooo commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationForConsistencyImpl.java
> + * Identity 수정 시 원서를 수정하는 service implementation 입니다.
아 실수했네요. 수정하겠습니다.

2023-09-17 06:47 UTC, jangwooooo commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CascadeDeleteApplicationServiceImpl.java
> +     * 매개변수로 userId를 받아 해당 userId가 작성한 원서를 찾습니다. <br>
넵 내부 구현에 관해서는 설명하지 않도록 수정하겠습니다.
피드백 감사합니다. 🙇🏻‍♂️

2023-09-17 06:48 UTC, jangwooooo commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CreateApplicationServiceImpl.java
> +     * 찾은 본인인증 정보와 원서에 작성할 정보를 바탕으로 원서를 생성하고 DB에 저장합니다.
넵 수정하겠습니다.

2023-09-17 06:48 UTC, jangwooooo commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationForConsistencyImpl.java
> +     * 원서를 찾았다면 기존 원서와 수정된 본인인증 정보를 바탕으로 새로운 원서 객체를 하고 저장합니다. <br>
네 오타네요.. 수정하겠습니다

2023-09-17 06:48 UTC, jangwooooo commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationStatusServiceImpl.java
> +     * 매개변수로 변경될 유저의 pk값과 변경할 원서상태 정보를 받아 userId로 원서를 찾습니다. <br>
넵 수정하겠습니다.

2023-09-17 07:46 UTC, YangSiJun528 reviewed
띄어쓰기 실수한 부분이 몇 개 보이네요.

2023-09-17 07:46 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CascadeDeleteApplicationServiceImpl.java
> + * 유저 탈퇴시 호출되는 원서 삭제 service implementation 입니다.
```suggestion
 * 유저 탈퇴 시 호출되는 원서 삭제 service implementation 입니다.
```
맞춤법 수정해주세요.

2023-09-17 07:46 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ApplicationListQueryImpl.java
> +     * 원서들을 pagination하여 반환해줍니다.
```suggestion
     * 원서들을 pagination하여 반환해 줍니다.
```
여기도 마찬가지로 띄어쓰기 수정해주세요.

2023-09-17 07:46 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/CascadeDeleteApplicationService.java
> + * 유저 탈퇴시 호출되는 원서 삭제 service interface 입니다.
```suggestion
 * 유저 탈퇴 시 호출되는 원서 삭제 service interface 입니다.
```

2023-09-17 07:54 UTC, jangwooooo commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/CascadeDeleteApplicationService.java
> + * 유저 탈퇴시 호출되는 원서 삭제 service interface 입니다.
수정하였습니다.

2023-09-17 07:54 UTC, jangwooooo commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ApplicationListQueryImpl.java
> +     * 원서들을 pagination하여 반환해줍니다.
수정하였습니다.

2023-09-17 07:54 UTC, jangwooooo commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CascadeDeleteApplicationServiceImpl.java
> + * 유저 탈퇴시 호출되는 원서 삭제 service implementation 입니다.
수정하였습니다.

2023-09-17 08:04 UTC, YangSiJun528 approved these changes
수고하셨습니다. 👍

2023-09-17 09:43 UTC, merged