[#5, #9] 단일 원서 조회 기능 추가
themoment-team/hellogsm-server pull request #52
Opened 2023-06-08 02:50 UTC by chanwoo00106

## 개요

원서를 하나만 조회하는 기능을 추가했습니다

## 본문

세부 로직이 똑같아 두 기능을 한 번에 구현했습니다
- 단일 원서 조회 기능
- 자기 자신의 원서만 조회하는 기능

### 추가

- .gitignore에 mock data를 넣기 위한 initMock 파일을 ignore 처리했습니다

### 변경

- applicantBirth 를 수정하면서 깜빡했던 부분을 수정했습니다
   - `hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationReqDto.java`

2023-06-08 08:08 UTC, YangSiJun528 commented
`ApplicationMapper` 중에서 좀 아쉬운게 있는데,
Application을 인자로 받고 ApplicationResDto를 반환하는 `ApplicationToApplicationResDto(Application application)` 메서드를 만들면 더 사용하기 쉽지 않을까요?
지금 코드에서 ApplicationResDto를 만들기 위해선 하위 엔티티 4개를 각각 따로 매핑해서 처리하는데, `ApplicationToApplicationResDto(Application application)` 메서드를 만들어서 사용하는 방식이 코드 가독성 면이나 효율 면에서 더 좋을 것 같습니다.
default 메서드를 사용해서 충분히 구현할 수 있을텐데, 어떻게 생각하시나요?

2023-06-08 08:13 UTC, YangSiJun528 commented
> `ApplicationMapper` 중에서 좀 아쉬운게 있는데, Application을 인자로 받고 ApplicationResDto를 반환하는 `ApplicationToApplicationResDto(Application application)` 메서드를 만들면 더 사용하기 쉽지 않을까요? 지금 코드에서 ApplicationResDto를 만들기 위해선 하위 엔티티 4개를 각각 따로 매핑해서 처리하고 있습니다. 이 방식보단 `ApplicationToApplicationResDto(Application application)` 메서드를 만들어서 사용하는 방식이 코드 가독성 면이나 효율 면에서 더 좋을 것 같습니다. default 메서드를 사용해서 충분히 구현할 수 있어 보이는데, 어떻게 생각하시나요?

물론 코드 수정/추가가 많이 발생할 수도 있지만, 지금처럼 하위 엔티티를 dto로 만드는 과정을 4번이나 반복해서 ApplicationResDto를 만드는 게 별로 좋아 보이지는 않네요.

2023-06-08 08:28 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
> +    public Object readOne(@PathVariable("applicationId") Long applicationId) {
`readOne()`이랑 `readOne()`의 리턴 타입으로 정확히 무엇이 올 수 있는지 주석으로 설명해 주세요.
리턴 타입으로 `Object`가 오는 이유는 이전에 이야기해서 알고 있지만, 정확히 리턴 타입이 무엇인지 알기 어렵습니다.

2023-06-08 08:35 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SingleApplicationGedRes.java
> +public record SingleApplicationGedRes (
해당 DTO를 반환하는 Mapper를 만들지 않은 이유는 무엇인가요? 
지금 코드로 보았을 때는 하위 dto를 만들고 제공하는 것으로 보이는데, 
`ApplicationToSingleApplicationGedRes(Application application)` 같은 메서드를 만들면 가독성과 효율이 더 높아질 것 같습니다.

2023-06-08 08:35 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SingleApplicationGeneralRes.java
> +public record SingleApplicationGeneralRes(
여기도 마찬가지입니다.

2023-06-08 09:23 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SingleApplicationGedRes.java
> +        GedAdmissionGradeDto admissionGrade,
그리고 제네릭을 사용해서 
GedAdmissionGradeDto와 GeneralAdmissionGradeDto이 모두 상속/구현하는 추상클래스/인터페이스를 만들고 이를 SupeGrade라고 할 때,  <? extands supeGrade> 티입를 반환하도록 하면 한 개의 Response DTO로 구현 가능할 것 같습니다.

참고로 SupeGrade가 아니라 자식들만 와야하니 아래처럼 작성하여 SupeGrade가 들어올 수 없도록 할 수 있습니다.
```java 
public boolean checkType(A a) { 
  if (a.getClass() == SupeGrade.class) { 
    return true; 
  } else { 
    return false; 
  }
}
 ```

2023-06-08 14:04 UTC, chanwoo00106 commented
두 dto가 가지는 상위 dto 를 만들어서 upcasting을 사용해서 해결했습니다

2023-06-08 23:16 UTC, YangSiJun528 approved these changes

2023-06-08 23:32 UTC, YangSiJun528 requested changes
fetch 조인을 사용하면 lazy loading인 객체도 eager하게 불러올 수 있습니다.
`QuerySingleApplicationServiceImpl`에서 하위 엔티티 따로 넣어주지 말고, fetch join으로 가져온 Application 객체를 인자로 SingleApplicationGrade를 생성할 수 있도록 변경해주세요.

2023-06-08 23:36 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SingleApplicationGrade.java
> +public interface SingleApplicationGrade {
이거 굳이 인터페이스로 반환할 필요 없어요.
어제 같이 코드 손봤을 때, 만들고 안 지운것 같아요.
`SingleApplicationRes` DTO는 다형성이 필요없어서 굳이 인터페이스를 사용할 필요 없습니다.
오히려 오해의 소지가 있을 수 있기 때문에 제거하는게 좋아요.

2023-06-09 00:13 UTC, chanwoo00106 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SingleApplicationGrade.java
> +public interface SingleApplicationGrade {
맞네요 
전부 지우는 커밋 날렸습니다~

2023-06-09 00:14 UTC, chanwoo00106 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
> +    public Object readOne(@PathVariable("applicationId") Long applicationId) {
리턴 타입이 추가가 되었는데 주석을 적어야 할까요?

2023-06-10 08:33 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
> +    default SingleApplicationRes CreateSingleApplicationDto(Application application) {
```suggestion
    default SingleApplicationRes createSingleApplicationDto(Application application) {
```
오타 수정해주세요.

그리고 다른 메서드랑 이름이 달라서 신경쓰이긴 한데, 나중에 통일할꺼니까 지금은 넘어가도 될 것 같습니다.

2023-06-10 12:39 UTC, chanwoo00106 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
> +    default SingleApplicationRes CreateSingleApplicationDto(Application application) {
나중에 통일하면 찾기가 힘들어 지금 하는 게 좋을 것 같습니다

2023-06-10 13:21 UTC, chanwoo00106 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
> +    default SingleApplicationRes CreateSingleApplicationDto(Application application) {
수정 완료했습니다

2023-06-10 14:00 UTC, YangSiJun528 approved these changes
확인했습니다.
그나저나 디코로 알려주시긴 했지만 코멘트에 답장도 달아주세요.

2023-06-10 14:22 UTC, YangSiJun528 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
> +    Optional<Application> findByUserIdEgerFetch(Long userId);
```suggestion
    Optional<Application> findByUserIdEagerFetch(Long userId);
```
오타 수정해주세요.

2023-06-10 14:23 UTC, YangSiJun528 requested changes
다시 확인해보니 오타같은 부분이 있어서 Request changes로 변경하겠습니다.

2023-06-12 00:12 UTC, chanwoo00106 commented on hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
> +    Optional<Application> findByUserIdEgerFetch(Long userId);
수정했습니다

2023-06-12 01:44 UTC, YangSiJun528 approved these changes
👍

2023-06-12 09:52 UTC, merged