[#6] 모든 원서를 조회하는 기능을 추가했습니다
themoment-team/hellogsm-server pull request #83
Opened 2023-06-20 05:34 UTC by chanwoo00106

## 개요

모든 원서를 조회하는 기능을 추가했습니다
원서 내용은 노션에 있는 Response값과 똑같이 했습니다

## 본문

- 모든 원서를 조회하기 위해 dto, service, controller를 추가했습니다

### 피드백

Responser값은 대충 아래와 같습니다

```json
{
	"info": {
		"count": Long, - 실물원서까지 제출한 유저의 수
	},
  "applications": []
}
```

이런 형식 때문에 applications 부분의 클래스 이름을 `ApplicationsDto`라고 했고
info 부분은 `ApplicationListInfoDto`라고 작성했는데 어떻게 생각하나요?

2023-06-20 05:44 UTC, YangSiJun528 requested changes
모든 원서 조회를 한다면 실제 운영 환경이라면 100~200 개가 조회될 텐데, 데이터 하나의 양이 많기도 하고, 전부 가져오기에는 서버 부하나, 요청을 전송하는데 데이터 양이 문제가 될 수도 있어요.

Pagination 기능을 추가해서 일부분만 가져올 수 있도록 하면 좋을 것 같아요. 

그 외에 딱히 문제될만한 부분은 보이지 않네요.

2023-06-20 05:49 UTC, YangSiJun528 commented
> 모든 원서 조회를 한다면 실제 운영 환경이라면 100~200 개가 조회될 텐데, 데이터 하나의 양이 많기도 하고, 전부 가져오기에는 서버 부하나, 요청을 전송하는데 데이터 양이 문제가 될 수도 있어요.
> 
> Pagination 기능을 추가해서 일부분만 가져올 수 있도록 하면 좋을 것 같아요.
> 
> 그 외에 딱히 문제될만한 부분은 보이지 않네요.

구현하면 List 대신 Page를 사용해야 해서 api 명세서가 좀 바뀔 수도 있는데, 아직 FE랑 연동 전이니까 좀 바뀌어도 괜찮을거 같긴 해요.
그리고 굳이 노션 api 명세서 수정 안해도 됩니다. 원서 도메인 작업 끝나면 Rest Docs로 전환할꺼에요.

2023-06-20 06:15 UTC, YangSiJun528 commented
> 모든 원서 조회를 한다면 실제 운영 환경이라면 100~200 개가 조회될 텐데, 데이터 하나의 양이 많기도 하고, 전부 가져오기에는 서버 부하나, 요청을 전송하는데 데이터 양이 문제가 될 수도 있어요.
> 
> Pagination 기능을 추가해서 일부분만 가져올 수 있도록 하면 좋을 것 같아요.
> 
> 그 외에 딱히 문제될만한 부분은 보이지 않네요.

paging 관련된 내용인데 참고용으로 올려드릴게요.

https://tecoble.techcourse.co.kr/post/2021-08-15-pageable/

https://hudi.blog/spring-data-jpa-pagination/

2023-06-21 00:34 UTC, chanwoo00106 commented
page nation 기능을 추가하는 걸 깜빡했네요
추가했으니 한 번 더 검토 부탁드립니다

2023-06-26 10:13 UTC, YangSiJun528 approved these changes
Approve한 줄 알고 있었는데 아니였네요. 늦게 확인해서 미안합니다.

2023-06-26 11:56 UTC, merged